---
name: Semgrep containers

defaults:
  run:
   shell: bash

on:
  workflow_call:
    inputs:
      branch_name:
        type: string
        required: false
      cancel_in_progress:
        type: boolean
        default: true
      semgrep_config:
        type: string
        default: p/default
      fail_severity:
        type: string
        default: error
      filter_mode:
        type: string
        default: added

  workflow_dispatch:
      
permissions:
  contents: read
  pull-requests: write

jobs:
  semgrep:
    name: Run Semgrep containers
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep:1.124.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: jq
        run: apk add --no-cache jq

      - name: Run Semgrep
        run: semgrep --config="$SEMGREP_RULES" --severity="${FAIL_LEVEL^^}" --json > semgrep-results.json
        env:
          SEMGREP_RULES: ${{ inputs.semgrep_config }}
          FAIL_LEVEL: ${{ inputs.fail_severity }}

      - name: Format Semgrep output to Reviewdog rdjson
        run: ./format-semgrep-to-rdjson.sh semgrep-results.json semgrep-rdjson.json

      - name: Run Reviewdog
        run: |
          reviewdog \
            -name="semgrep" \
            -reporter=github-pr-review \
            -fail-level=error \
            -filter-mode=added \
            -f=rdjson < semgrep-rdjson.json
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMGREP_RULES: ${{ inputs.semgrep_config }}
          FILTER_MODE: ${{ inputs.filter_mode }}
          FAIL_LEVEL: ${{ inputs.fail_severity }}
